### PR TITLE
Feature/add new type of generate specs WIP

### PR DESCRIPTION
**Pull request by manudss**
Hi, 

Your script looks awesome, and I would help you, and contribute. 
I am currently working, on generate more type of specs, and more complete. In this first version the testbed version. 

What do you thinks ? 

Emmanuel

### CODE REVIEW

**Comment by gparlakov** [comment]
Hi. Thank you for taking the time. 

I'll try to look into the PR as soon as I can and get back to you. Probably after the week end.

**Comment by manudss** [comment]
If you want, I have contacted you by gitter. To discuss more about it. 

Emmanuel

**Comment by gparlakov** [comment]
Hi.

Ive been following your efforts and thank you again for your time and
interest in my project. Thanks 😊 for making me proud.

Sorry for the late reply.

How am I supposed to accept this PR? Please help me understand what is it
you are aiming for?

**Comment by manudss** [comment]
Hi @gparlakov  
It would be easier to talk to each other via another way, I contacted you on Gitter. But we can also contact us by another means.
I would like to speak a little more with you, about what I would like to do! Changes that could be made, changes that I would like to make in order to be in agreement.

The goal I would like is to have a tool to generate the tests : which generates all the necessary code for the unit tests, and that we are then just need to write the unit tests.
With the current version of scuri, when used on my project, it did not generate tests that worked, 
Maybe first because it does not use the standard testbed method.

This first pull request, adds a possibility to have several types of template for the generation of tests. Like that, it allows to have several method to choose the one which is best for its use.
Then generate a little more code, to go further compared to what you have already done.
Like the function parameters, if it returns data, and then see if we can generate more, like the functions that are called in the function to test and other things.

This pull request is not ready yet, but I created it so that you can see and give me your opinion on what I propose.

**Comment by gparlakov** [comment]
@manudss Emmanuel, thanks for your ideas.

I see that you continue pushing commits to this branch. But how am I supposed to merge a PR of this size?

**Comment by gparlakov** [comment]
>The goal I would like is to have a tool to generate the tests : which generates all the necessary code for the unit tests, and that we are then just need to write the unit tests.
With the current version of scuri, when used on my project, it did not generate tests that worked,
Maybe first because it does not use the standard testbed method.

This looks like we can start discussing.

Can you provide an example of what a component would look like and what you'd like the test to look like?

**Comment by gparlakov** [comment]
Here's how I do the workflow 
 - find a bug/feature to fix/add 
 - create an issue
 - fix/add it and add test to make sure next iterations do not break it

**Pull request closed without merging**
